name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install

      - name: Build vike-solid
        run: pnpm run build

      - name: Test building examples/full
        run: pnpm run build
        working-directory: ./examples/full
      - name: Test building examples/minimal
        run: pnpm run build
        working-directory: ./examples/minimal

      - name: Test TypeScript examples/full
        run: pnpm run test
        working-directory: ./examples/full
      - name: Test TypeScript examples/minimal
        run: pnpm run test
        working-directory: ./examples/minimal